version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    restart: always
    networks:
      - api-gateway_backend

networks:
  api-gateway_backend:
    driver: bridge
    external: true
