version: '3.9'

services:
  api-gateway:
    container_name: api-gateway
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge