version: '3.9'

services:
  auth:
    container_name: auth
    build:
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh authdb ./bin/api
    ports:
      - "50052:50052"
    environment:
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - authdb
      - redis
    restart: always
    networks:
      - auth-grpc_backend
      - payment-grpc_backend
      - api-gateway_backend
  
  authdb:
    image: postgres:15.1
    container_name: authdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=authdb
      - PGDATA = "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./migrations/000001_authdb.up.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - auth-grpc_backend

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=examplepass
    restart: always
    networks:
      - auth-grpc_backend

volumes:
  pgdata:
networks:
  auth-grpc_backend:
    driver: bridge
    external: true
  payment-grpc_backend:
    external: true
  api-gateway_backend:
    external: true